### Site Settings ###
title               : nh4ttruong
description         : >-
                      :coffee: is not only coffee, but also my life. By the way, welcome to my space :rocket:
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : nh4ttruong/nh4ttruong     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU@v2.3.0
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name              : Nhật Trường
  image             : https://i.imgur.com/V60Nk1V.jpg #https://i.imgur.com/0HFIXeg.jpg
  email             : truongtbn243@gmail.com
  facebook          : nh4ttruong
  github            : nh4ttruong
  instagram         : nh4ttruong
  youtube           : nh4ttruong

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - LICENSE
  - "*.log"
